# Use the official Python image from Docker Hub
FROM python:3.8

# Set the working directory inside the container
WORKDIR /app

# Copy your Python script and requirements file into the container
COPY . ./

# Install dependencies
RUN pip install -r requirements.txt
