# Use an official Node.js runtime as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Expose the port the app runs on
EXPOSE 3000
EXPOSE 24600


# Define the command to start the app
# CMD ["npm", "run", "dev"]
